### ISSUE TITLE
Rope for Vec<u8>

### ISSUE THREAD

**Issue by duesee** [google/xi-editor#153]
Hello, is it discouraged to use the rope for simple byte- instead of utf8 sequence? I would like to use it in a hex editor but am not sure, if it is strictly specialized. If so, is it feasible to make the rope generic? Or would it be simpler to fork and remove all utf8 handling?

**Comment by raphlinus** [comment]
It would totally make sense to use the rope data structure for byte editing. However, you don't want to use `Rope` for this, which is specialized to strings, but rather you'd want to do your own `Leaf` and `NodeInfo` and use them in your own instantiation of `Tree<NodeInfo>`. If I were doing it, I'd go further and support `Vec<T>` rather than only `u8`, as most of the rope operations should be generic (as is `Vec`).

It shouldn't be all that difficult to implement these traits, but the documentation is sadly a bit sparse. If you did add them, I'd happily accept the PR. It should also be possible to develop these in your codebase and just rely on `Tree<>`.

**Comment by duesee** [comment]
Hello, I'm relatively new to Rust and not sure if I can make it. But I will give it a try next weekend :-)

**Comment by duesee** [comment]
Hello raphlinus. I started to look at the code more closely. As far as I understand, the code in `lib.rs` is an old implementation which should eventually be deleted, right? Is there a reason the example in `ropetoy.rs` uses the old implementation? Since I wanted to experiment with the lib anyway, I could provide a new example if you like.

**Comment by raphlinus** [comment]
@duesee Not a very good reason. The only reason I haven't deleted the old version is that there are some optimization tweaks and tests that are still not as good in the new one.

In any case, you should be able to get pretty far by copying rope.rs, switching from String to Vec, and getting rid of all the string-related and UTF encoding methods.

**Comment by cmyr** [comment]
Closing as stale.
