### ISSUE TITLE
no cursor when creating new window

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#161]
The code that draws the cursor doesn't execute if there are no lines in the in the LineCache, which there aren't until any text has been entered into the window. 

A possible fix would be to initialize with a single empty line?

**Comment by raphlinus** [comment]
Yeah, this happened with the new update protocol.

There are (at least) three ways to fix it, I'm not sure which is better.

Choice 1: initial state is zero-length line list, no cursor is drawn, but core sends the diff to be a length 1 list with just a cursor immediately after creating a new tab (that's the new tab behavior; on loading a file, it might send the diff to show the file). If the core is very slow, there might be a gap where no cursor is shown.

Choice 2: if the line cache is empty, the front-end draws the cursor anyway.

Choice 3: the initial state of a line cache is a single empty line with a cursor. The first delta sent by the core will be against that rather than against the empty list.

I'm leaning toward 1 here because it's the least work for front-ends, they don't have to do anything special.

**Comment by cmyr** [comment]
I think option 1 is also clear conceptually, since the cursor _is_ present even if the buffer is empty.
