### ISSUE TITLE
reversed iterator?

### ISSUE THREAD

**Issue by hh9527** [google/xi-editor#177]
for now, there is a `Rope.iter_chunks` method, but there isn't a `Rope.rev_iter_chunks`, so it is very hard to implement something like `delete_to_begin_of_line` efficiently.

for vim users, `text-object` is a very powerful feature:
for example: `vaw` which means  `visual select a word`, can be implemented as the following instr sequence:
- begin = back_search_word_begin(buffer)
- end = search_word_end(buffer)
- select_open_open(buffer, begin, end)

Without `Rope.rev_iter_chunks`, it may be implemented with `Rope.byte_at`, but it will be `O(n * Log(n))` on every byte.

**Comment by raphlinus** [comment]
I'm not understanding what the problem is. There's already an implementation of `delete_to_beginning_of_line` and I'm not aware of any performance problem with it. I'm similarly not aware of any problem with functions like `move_word_left`, which is a pretty thin wrapper around `WordCursor::prev_boundary()` etc.

It's certainly _possible_ to implement a reverse iterator on chunks, but for the kinds of things you're talking about, it seems to me to make more sense to use a `Cursor` abstraction, of which there are a number in xi. I've also used this cursor pattern in https://github.com/unicode-rs/unicode-segmentation/pull/23, which will become the grapheme logic in xi.

**Comment by hh9527** [comment]
Oh, my mistake. I didn't realize that tree::Cursor has the ability to traverse backward.
