### ISSUE TITLE
`new_tab` rfc should have `for_open` param

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#186]
Another plugin consideration: I'm thinking about plugin and editor lifecycle. Currently if we open a file, we send a `new_tab` followed by an `open` rpc. If we create a new file, we only send `new_tab`.

I would like there to be a lifecycle event that predictably happens once for each newly opened buffer. If that buffer is being opened, this should be called when the open operation has completed; if the buffer is new it should probably be called when the `Editor` is instantiated. 

One of the things that would occur in this method (per my current sketch of an implementation) is that the plugin catalog would generate a data structure representing the loaded and loadable plugins and available methods/commands/menu items/etc available in this buffer. As things are currently implemented, this would always have to be generated twice in the case of a file being opened, because there's no way of knowing if a `new_tab` is for a new buffer or for opening an existing file.

Let me know if I'm missing anything obvious. (Also: non-obvious).

**Comment by raphlinus** [comment]
I'm sympathetic, though maybe don't understand perfectly why this is needed.

One thing to keep in mind: somewhere on the roadmap, I want to implement fully async loading. This would be an astonishing win for file-open latency with large files; you'd see the head of the file instantly no matter how large the file is, and basically only the scrollbar would animate (I consider animating the scrollbar to be a good visual indicator of loading progress). That said, it's not going to be anytime _soon_ on the roadmap because it adds quite a bit of complexity. In particular, it complicates the notion of when file loading is "done" (especially from the perspective of plugins). For a pure syntax highlighting plugin, it would be great to start the highlighting work immediately and display those results. However, for something like a lint tool, you'd want to wait til loading is complete, to prevent the tool from seeing a truncated version of the file.

**Comment by cmyr** [comment]
I would consider this issue superseded by #191; the larger issue here was that the current implementation of creating vs opening files didn't provide a clear place for _any_ `file_open` notification we might want to send to a plugin.

Async open would be nice to have. I think sending a `began_open` with the first chunk of file and then a final `did_open` on success would be acceptable?

I'm going to close this, but I'll open one for async file opening.
