### ISSUE TITLE
State of line wrapping?

### ISSUE THREAD

**Issue by IGI-111** [google/xi-editor#207]
I just read [Rope Science 6](https://github.com/google/xi-editor/blob/master/doc/rope_science/rope_science_06.md) and it described what seems like a very neat way of solving that annoying but common text editor problem of wrapping lines.

Unfortunately digging into the rest of the documentation I couldn't find much about it (like enabling/disabling wrapping, or asking for a certain width) and then in the in the code I could only find some rewraping functions and a `DebugRewrap` command. 

So I guess I'm wondering what the correct way to deal with wrapping lines is at the moment if there is one.

And as a bonus: are there any plans on how to deal with mouse interaction on wrapped lines? Translating the coordinates of the view on the fly has got to be painful, hasn't it?

**Comment by cmyr** [comment]
There's experimental line-wrap support available in the debug menu, but it isn't tightly integrated yet. It's definitely planned for 'soon' (for some value of soon), though.

A current issue with doing line wrapping well is in supporting non-monospaced type: the only way the backend can know how wide a particular sample of text is is to ask a particular front-end to measure it, because display width will depend on a bunch of factors like the properties of a particular font-face and the platform specific rendering behaviour. This isn't too bad (you can do a bunch of caching) but it will take a bit of work to get right.

For mouse interactions, all events in some client coordinate space are converted into byte offsets internally anyway; this is already line-break aware, afaik.

**Comment by jansol** [comment]
This can probably be closed?
