### ISSUE TITLE
Emoji input does not work

### ISSUE THREAD

**Issue by robjperez** [google/xi-editor#21]
Try to enter any emoji character either by copying and pasting or by typing it directly. It does not work

**Comment by rtsuk** [comment]
I'm guessing we'll have to implement NSTextInputClient for most fancy text input methods to work.

Copy and paste isn't implemented at all, but that should be its own issue.

**Comment by Sineaggi** [comment]
The backend itself handles emoji just fine, it can handle emoji characters being sent to and loaded from files. The only problem I've been experiencing is that the characters themselves don't have the same width as the other monospace characters.
![xiwin_emoji](https://cloud.githubusercontent.com/assets/889237/15062001/f4cc05be-12f8-11e6-9edd-1240fcba7673.PNG)
This issue is also prevelant in Sublime Text, and they make some attempt to keep text grid aligned.
![sub_emoji](https://cloud.githubusercontent.com/assets/889237/15062014/20a95394-12f9-11e6-912f-698654c62099.PNG)

**Comment by raphlinus** [comment]
I'll also note that copy-paste now works.

I'm not sure what's the right approach to width. My gut feeling is that emoji (like many other scripts) just doesn't fit into a grid-aligned world. Ideas welcome.

**Comment by raphlinus** [comment]
This should be fixed by #70.
