### ISSUE TITLE
How is highlighting information representend?

### ISSUE THREAD

**Issue by amirouche** [google/xi-editor#212]
Héllo,

I'd like to know how highlighting information is represented in xi editor.

Thanks in advance.

**Comment by raphlinus** [comment]
The action item for this issue is to improve the documentation on the question. That's in a bit of flux right now; at the moment, the plugin sends style spans to the core as json objects (parsed at https://github.com/google/xi-editor/blob/master/rust/core-lib/src/editor.rs#L928), while the core sends set_style (as described in https://github.com/google/xi-editor/pull/152) only for unique styles, then sends the styles to the front-end in an efficient "triples" encoding using one array per visible line. When the next set of changes lands, the plugin will also have a set_style method for new unique styles, and use a similar triples encoding to set styles.

I know this doesn't fully answer your question, but hopefully points you where to look. Thanks for your interest.
