### ISSUE TITLE
Unexpected cursor position/movement on redo

### ISSUE THREAD

**Issue by rkusa** [google/xi-editor#232]
![2017-04-25 20 21 06](https://cloud.githubusercontent.com/assets/409021/25401037/d1d5ca7c-29f4-11e7-8cb1-d9a1a5abcf7e.gif)

1. Write a word
2. Move cursor into the word and delete a character
3. Undo twice (should re-add the charachter and then remove the word)
4. Redo once (word will re-appear but with cursor at wrong position)
5. Write another character -> the cursor jumps to the end of the word and adds the character there

I might have a look at this issue myself in the next couple of days, but have to learn how undo/redo is implemented first .

**Comment by raphlinus** [comment]
Without digging into the code, I have a suspicion what's the problem. The logic in `View::after_edit` for updating the cursor after an edit is pretty primitive. For most editing operations, it doesn't matter, because the edit explicitly sets the cursor anyway. Undo/redo is a major exception.

I'm planning to completely redo `after_edit` to operate directly on the (multi) selection as part of #188, doing fancier OT (and, among other things, using the high precision delta rather than the summary, as updating multiple cursors after multiple local edits is important). So I wouldn't spend too much time on this right now; any code involving sel_start and sel_end is definitely going to be changing soon.

**Comment by cmyr** [comment]
Fixed, presumably in one of #259, #260, #305, #321 or #322 😎
