### ISSUE TITLE
use serde serialize/deserialize to parse RPC commands

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#251]
Currently in [various](https://github.com/google/xi-editor/blob/master/rust/core-lib/src/rpc.rs#L123) [places](https://github.com/google/xi-editor/blob/master/rust/core-lib/src/run_plugin.rs#L131) we do a bunch of manual json parsing. A lot of this code predates Serde, which offers a much more ergonomic solution, via [serialize/deserialize](https://serde.rs/derive.html).

This is a nice-to-have, but if anyone is looking for a little project it's a very contained bit of work.

**Comment by chriskrycho** [comment]
@cmyr, want to write up any particulars? I'd really like to tackle this and will have some time over the next few weeks.

**Comment by cmyr** [comment]
@chriskrycho I haven't dug too deep into this myself. The approach I would take (apologies if this is exceedingly obvious/high-level):

- give a good read through the docs linked above, with special attention to the section on [enums](https://serde.rs/enum-representations.html).
- experiment, starting in [core-lib/src/rpc.rs](https://github.com/google/xi-editor/blob/master/rust/core-lib/src/rpc.rs#L122) with adopting `#[derive(Deserialize)]` for CoreCommand + the related command enums. This might work reasonably well right away, or you might have to fiddle with various [attributes](https://serde.rs/attributes.html), or you _might_ discover that the way those enums are nested doesn't match very well with the underlying json, in which case we'll have to modify one or both, or reconsider this approach.
- (optional) if you're worried about breaking anything, it should be quite easy to write some tests based on the current behaviour; assuming you're using xi-mac, I would log the raw json the client is sending, and write a few tests for various types of commands that just parse that and assert the appropriate result.
- Use this issue or irc to discuss any problems you run into.

Let me know if you have any other questions!

**Comment by ax487** [comment]
Well, sifting through the code I would like to ask some questions: 

It seems like the `xi-core-lib` crate depends on `xi-rpc`. However, the structures which are fundamental for RPC parsing, such as [`pub enum Request<'a>` ](https://github.com/google/xi-editor/blob/master/rust/core-lib/src/rpc.rs#L40)and [`pub enum CoreCommand<'a>` ](https://github.com/google/xi-editor/blob/master/rust/core-lib/src/rpc.rs#L46) are defined
in `xi-core-lib` itselft and *not* in `xi-rpc`. 

This means that these structures are not available in `xi-rpc`, as including `xi-core-lib` would introduce a dependency cycle. 

For this reason it seems that the parsing of messages is performed at a lower level (without using the designed structures) in `xi-rpc` by [`parse_rpc_request`](https://github.com/google/xi-editor/blob/master/rust/rpc/src/lib.rs#L126) and alike. In a second step the structures are assembled from the preparsed expressions.

I guess that in order to simplify matters some refactoring would be required. Specifically, the above structures would have to be moved into `xi-rpc`. This would make change somewhat intrusive and less isolated. @cmyr: Is that what you had in mind or would changes in either `xi-core-lib` or `xi-core` suffice?

**Comment by cmyr** [comment]
@ax487 I've actually been slowly working on a new approach to rpc parsing/handling that uses macros and makes better use of the type system (a sort of sketch is available here: https://gist.github.com/cmyr/c5d28931826fb6ac410d9bda9e389d79) but that work has stalled a little bit as I've been busy the last few weeks.

That said, I'm not sure this issue makes a great jumping-in point at the moment. If you're interested in finding something to work on, maybe jump on the IRC channel and we can try and figure something out?

**Comment by cmyr** [comment]
Closed in #393
