### ISSUE TITLE
xi-unicode line break unit test failures

### ISSUE THREAD

**Issue by cbreeden** [google/xi-editor#262]
I wrote a test which parses the unit tests from UAX-45 found [here](http://www.unicode.org/Public/9.0.0/ucd/auxiliary/LineBreakTest.txt), and compared them with the results from `xi-unicode::LineBreakIterator`.  There were 122 failures.  I posted the failures in this [gist](https://gist.github.com/cbreeden/46e895cbf07b40072dc0e4d4cace761a).

It's possible that there could be a bug in my unit tests, though I have verified a few of the failures by hand.  I have included the source for the tests in the gist -- just be sure to include [LineBreakTest.txt](http://www.unicode.org/Public/9.0.0/ucd/auxiliary/LineBreakTest.txt) in the `tests/` directory.

I can open a PR for including the unit test if desired.

One possible source of false positives for these tests is the allowance of some [customizations](http://www.unicode.org/reports/tr14/#Customization).  These will need to be verified individually.

**Comment by cbreeden** [comment]
Changing [this line](https://github.com/google/xi-editor/blob/master/rust/unicode/tools/mk_tables.py#L370) from

```python
            elif R == 'CM' and L not in ['BK', 'CR', 'LF', 'NL', 'SP', 'ZW']:
```
to
```python
            elif (R == 'CM' or R == 'ZWJ') and L not in ['BK', 'CR', 'LF', 'NL', 'SP', 'ZW']:
```
reduces the number of failures to 53.  The new line seems to more accurately reflect [LB9](http://www.unicode.org/reports/tr14/#BreakingRules).

I will need to verify that this is a strict subset of errors, and probably run it through the fuzzy tests as well.

**Comment by raphlinus** [comment]
I suspect that most of these failures are due to Unicode 8->9 changes, and the followup about ZWJ is consistent. I hand-tested against the Unicode 8 corpus when I was developing it.

I don't have a lot of customizations or tailoring. In fact, I explicitly decided against adding more breaks in the punctuation / number combinations as in ICU, as it complicates the logic a lot and I believe the new breaks are not robust in all use cases.

I would definitely welcome a PR that added explicit testing.

Thanks for digging into this!
