### ISSUE TITLE
Heresy: Why not have the core be a library instead of a separate process?

### ISSUE THREAD

**Issue by trishume** [google/xi-editor#301]
So, there's been a lot of discussions about all the unfortunate and difficult things Xi will have to do to deal with the fact that the frontend and core communicate asynchronously over IPC. 

What if the core was a (dynamic) library with a very small C interface along the lines of:
```rust
fn send_msg(msg: String) -> String {}
fn check_notifications() -> Option<String> {}
```

The frontend and backend would still communicate over the exact same json-rpc interface, it would just be faster and have the ability to do synchronous RPC calls without run loop shenanigans.

### Pros:
- Completely eliminates the need for caching in the frontend. Removing all that complexity and fixing the Cocoa issue that would require all sorts of fancy prediction in order to avoid painting blank areas when scrolling.
- Removes the potential need for a separate dynamic library for the core to do text measuring, it can be a low-overhead function call RPC just like everything else.
- Allows synchronous handling of key bindings, which was noted on IRC as desirable but not nice with the current architecture.
- If you really want to separate the two for some reason (I don't know why you would) you could write a tiny dylib that uses blocking I/O calls to forward this interface to another process, at the cost of overhead.

### Cons:
- Marginally increases the difficulty of writing the core-interface part of a frontend. But even in languages where binding to C is difficult, two functions shouldn't be too hard.
- On platforms that don't support dynamic libraries, would require static linking, which would mean the code pages for xi-core wouldn't be shared among many instances of the frontend. This could only really plausibly be an issue on Fuchsia, and even then I don't know if this is a real issue.
- Harder to run xi-core on a different machine, but that was already bound to be a fairly crappy experience. It would make much more sense for the remote editing story to be based on having both a local and remote instance of xi-core that synchronize by CRDT and some plugins/commands (text manipulation) are run locally while others (save, autocomplete, find in project) are run remotely.

### Tradeoff Analysis

I think the added difficulty of linking a dynamic library and binding to a tiny C interface is waaay easier in every language one would reasonably write a frontend in than writing a line cache, scroll prediction, separate font measuring dylib, etc. 

Life is way easier if the frontend can assume that certain calls (eg. request lines, process keystroke) will return near-instantaneously. For calls that do actually require time to process, those can still be done asynchronously exactly as before by having the result of `send_msg` be a request ID and then waiting for the corresponding result as a `check_notification`.

### What am I missing?

At the moment I can't think of any more reasons (not listed above) not to do this, the tradeoff seems to be in favour of a library. However, I know that doesn't mean there are no good reasons not to. Can anyone think of any? And maybe @raphlinus can enlighten us with why he didn't choose this design in the first place.

**Comment by raphlinus** [comment]
This is a complex question, and it _could_ go both ways. I'll try to address it.

First, I think this question conflates two separate issues, one of which is central to the design of xi, and one of which is more incidental:

* Are the front-end and core tightly coupled, using mostly synchronous communication, or loosely coupled, using mostly asynchronous communication?

* Are the front-end and core in the same process with linking, or in different processes, with interprocess communication?

Note that these decisions can mix in any combination. There's nothing that would prevent all front-end actions delegated as synchronous RPC's to a separate process, though of course this particular combination would be particularly hard to make performant. Also, loosely coupled async with the core in process is exactly how [xi-win](https://github.com/google/xi-win) is built.

For the former question, I feel that loose coupling is essential to the design of xi. Yes, we expect the core to respond quickly in most cases, but there will be cases where it cannot (zillions of cursors, disk i/o being very slow, pathological text such as zalgo). In those cases, the UI should still be responsive.

### The proposed C interface is missing notification

The proposed `check_notifications` call is a polling model, but there's no indication here of _when_ results would be ready. This can be added, but then the "run loop shenanigans" are back.

### FFI and stability

FFI is notoriously a large source of instability; two languages which might themselves be memory-safe or reasonably close (Swift and Rust) are much less so when linked together with FFI. This is even more true when there are multiple threads involved; races involving lifetimes.

### Symmetry with plugins

The xi design requires plugins to be loosely coupled and indeed out-of-process (an editing session should smoothly survive a plugin crash). So we have one mechanism for coupling modules together; the above proposal would be two.

### Synchronous RPC's in the current model

I'm trying to explore just how much can be done with purely asynchronous RPC communication. However, it's starting to look like certain things simply require a synchronous result for the most polished UX - misses in the line cache and handling modal keystrokes. These can be done, that's why the RPC mechanism has both synchronous and asynchronous calls. I basically just wanted to explore how far we could go with pure asynchrony.

### Overhead

I haven't done extensive measurement, but assuming that communication is serialized and in separate threads, the extra overhead for multi-process communication should be minimal.

### The line cache

It is not the case that synchronous access to the document would obliviate the desire for a line cache. The existing front-ends are not there yet, but the evolution of line caches is that they hold downstream, ready-to-render representations of the text (CTLine, TextLayout, etc). This will reduce the overhead for constantly redoing layout of the text when scrolling etc.

### Measurement dylib

Yes, if we go the dylib route for measurement, then having front end and core in the same process starts making infinitely more sense. However, I think this can also be done asynchronously.

## Conclusion

It's worth asking these questions, because there are inevitably tradeoffs. The extremely async design poses challenges, some of which would be much easier in a more sync design. However, I think these problems are solvable, and I think they're worth solving to make the end experience as close to ideal as possible.

The question of in-process vs two-process is more of an implementation detail, which I see as a pure tradeoff involving stability, build difficulty, and performance. I don't believe this decision profoundly affects the rest of the design or the experience, as we can do synchronous RPC's as needed. We just want to minimize them, to optimize UI smoothness.

**Comment by trishume** [comment]
Thanks, that clears things up. Those arguments are sufficiently convincing. The most convincing one is that an efficient implementation will need a line cache anyway to store text data structures, which tips the tradeoff significantly since I thought one of the main advantages would be avoiding a line cache and scroll prediction.

I'm still in favour of not trying too hard to avoid synchronous RPC calls though for things that have low worst-case latency, like key processing.

I agree with your separation of coupling and process structure. One worry I have though is that, as was discussed in the context of line cache misses in Cocoa, that run loop and UI structure will make synchronous calls very difficult in some scenarios when done out of process.

Perhaps there should be a "Design FAQ" doc in the repo containing copy-pastes of discussions on design decisions.
