### ISSUE TITLE
set_scroll is inconstant with what is exposed to front-end

### ISSUE THREAD

**Issue by pforpallav** [google/xi-editor#315]
Front-end never receives hints on what line-range it is on. Are we adding support for this or am I missing something?
If not, call to `set_scroll` with `first` and `last` lines to be drawn, requires more state to be managed by front-end. We can make the `set_scroll` call in units relative to the current viewport, right?

**Comment by raphlinus** [comment]
If you're talking about the existing behavior of xi-win, what's there is very much a temporary placeholder. The scroll state needs to be owned by the front-end, not the core, and the line cache really needs to be treated as a cache.

We could use the line cache from gxi, but I have in mind writing my own that's fancier in being able to process the lines, for example on Windows storing DWrite TextLayout objects (plus geometry for cursors and selections).

**Comment by pforpallav** [comment]
Its more of a generic question when looking into the way various front-ends have implemented growing and shrinking of viewport. Frontends have to recalculate the lines in the new viewport and request lines depending on that. And since line number is not a property of the `line` struct, it needs to keep a state for line-nums in the view and update it whenever updates are pushed to `line_cache` from the view back-end . If view is owned by the back-end, why is it good to have this state (scroll state) on the front-end?

**Comment by raphlinus** [comment]
To address these: on viewport size change, the front-end should just be able to send a "scroll" with the new viewport, and the core should automatically supply new lines (and only the new lines). I don't believe the front-end needs to do a calculation of which lines are needed.

Line number information needs to be added to the `line` struct, so that it represents the source line. Current situation is temporary. That's tracked in #184.

It's not 100% accurate to say view is "owned" by core, probably better to say that both front-end and core have representations of the view that are kept in sync. The authoritative version of the scroll state needs to be owned by the front-end so that it can respond to scroll requests as quickly as possible, without waiting for a roundtrip to the core in the cache-hit case (and there's more work to be done to make cache-hit more likely).

Hope this clarifies things a bit.

**Comment by pforpallav** [comment]
Thanks a lot! This definitely clears loads! 😄 I am going ahead and closing this issue as there are other tasks like #184 which will settle issues here.
