### ISSUE TITLE
remove plugin-applied spans on plugin exit

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#318]
Exiting a plugin currently leaves all of that plugin’s spans in place. Spans should have an `author` tag, and spans should be removed when their `author` exits.

A similar mechanism should be involved in cleaning up all plugin-generated resources on plugin exit. Spans is the only of these resources currently implemented.

**Comment by trishume** [comment]
I wonder if there's some way to store different "layers" of spans separately, and iterate a bunch of them at once. Then it would be super fast to clean up spans that should be removed.

This pattern of wanting fast "delete everything I did" actually occurs in many places. For example un-highlighting find+replace matches. As well, sometimes plugins will probably want to invalidate all their annotations and re-do them from scratch, because making things incremental is hard.

**Comment by raphlinus** [comment]
I think layers are correct here, for a variety of reasons. And yes, on unexpected plugin exit, the spans should go away.
