### ISSUE TITLE
implement `select_next` command

### ISSUE THREAD

**Issue by eyelash** [google/xi-editor#325]
I'm talking about the command that is triggered with ctrl-D or cmd-D on most editors. It selects words if the last selection is a caret and otherwise searches for the last selection and adds a new selection for the next occurrence.

**Comment by callodacity** [comment]
I think it would be important to create a distinction like Sublime Text does:

* If the user starts with an empty selection, then `cmd+d`/`ctrl-d` will search by whole words. 
* If the user starts with a non-empty selection, then it will search for any instance of the text.

For more information, see these:
* https://stackoverflow.com/a/18422707/5552584
* https://forum.sublimetext.com/t/bounded-quick-add-next/8609/6

**Comment by trishume** [comment]
@eyelash whoah that's super weird that there's a difference between selecting `bcd` using `ctrl+d` and double-clicking, interesting. That seems unintuitive and I have no idea what difference in internal state is going on there. Thanks for pointing it out!

I wonder if that's an intentional design choice or just a quirk of the way they implemented it. I can actually kind of see that behavior being handy in some cases. If I don't think about consistency it does what I think I'm most likely to want in those two cases.

That seems like something that can be an extension of the behavior later and isn't necessary to replicate for an initial implementation, if we do want to replicate it.

**Comment by eyelash** [comment]
Both Atom and Sublime Text also have a [command bound to Ctrl+K Ctrl+D](https://stackoverflow.com/q/11548308/799849) that selects the next find but skips the current one. It would be nice to have this command in Xi as well.

**Comment by cmyr** [comment]
That could maybe be a flag? In any case, good feature.
