### ISSUE TITLE
Consider kakoune mode

### ISSUE THREAD

**Issue by zellyn** [google/xi-editor#337]
Not only is [Kakoune](http://kakoune.org/) an interesting and ambitious redesign of a modal editing UI, but many of the features, such as multiple selections and especially selection splitting, would be an interesting test case for Xi: if you can cover Kakoune functionality, you should be able to cover anything!

**Comment by trishume** [comment]
I definitely think there is interest and we've discussed doing this before. It informed some of our discussion of wanting to support custom key bindings and discussions of how to support key bindings of `alt+key` that might otherwise conflict with unicode or menu accelerators. I know @raphlinus has said he's interested in Kakoune bindings.

**Comment by cmyr** [comment]
The very loose plan here is to implement a general framework for modal editing support that can be adapted to any number of particular implementations, of which kak is the second obvious target, after vi.

**Comment by cmyr** [comment]
for reference the discussion issue for modal editing is #302.
