### ISSUE TITLE
core should send client list of available themes

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#360]
This is related to #353; core should notify client of available themes on launch, and whenever the set of available themes changes.

**Comment by z3t0** [comment]
This might be the wrong place to ask about this, but it's relevant to theming so might as well start here. I watched the video by the original creator of this project about how the main goal was performance and that breaking the project into components was a part of achieving this. 

I was thinking about why the "core" server needs to have control over visual elements, such as theming. For example, why doesn't the syntax highlighting plugin connect to the front end, and not the backend. The reason for this is of course is because generally speaking the backend does not need to know about the specifics of the graphical display. Instead it can focus on say tokenising the source text which can be sent to the front end. And the front end can deal with a tokenised but graphics agnostic input and run it through a syntax highlighter.

To be clear, this might be a completely unnecessary and premature way to handle things, but it also has the benefit of further decoupling the UI. However, I do believe that too much fragmentation is not to be desired.

Thoughts?

**Comment by trishume** [comment]
@z3t0 the reason for having a separate frontend is so that there can be a native frontend for every platform. In order for that to happen without a huge amount of effort, writing a frontend has to be really easy and can't necessarily rely on the frontend being written in Rust, for example because the UI toolkits of certain OSs work way better in one language (e.g macOS/Swift, Android/Java, Fuchsia/Dart).

Every responsibility we give to the frontend has to be rewritten 3 times and marginally decreases the number and quality of frontends that will be written. Having the frontend communicate with plugins would replicate all the plugin communication and styling code.

Also the core has all the best data structures to put visual information in so that it can be updated asynchronously and efficiently.

**Comment by trishume** [comment]
@z3t0 the reason for having a separate frontend is so that there can be a native frontend for every platform. In order for that to happen without a huge amount of effort, writing a frontend has to be really easy and can't necessarily rely on the frontend being written in Rust, for example because the UI toolkits of certain OSs work way better in one language (e.g macOS/Swift, Android/Java, Fuchsia/Dart).

Every responsibility we give to the frontend has to be rewritten 3 times and marginally decreases the number and quality of frontends that will be written. Having the frontend communicate with plugins would replicate all the plugin communication and styling code.

Also the core has all the best data structures to put visual information in so that it can be updated asynchronously and efficiently.

**Comment by z3t0** [comment]
Alright thanks for the explanation

**Comment by cmyr** [comment]
closed in #386
