### ISSUE TITLE
reload files if changed outside the editor

### ISSUE THREAD

**Issue by jansol** [google/xi-editor#362]
Another very common and very useful feature. Needs a way to have the frontend ask the user if they actually want to reload the file, though.

**Comment by prasoon2211** [comment]
We can probably use a combination of [last modified](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.modified) timestamp and md5 of file contents to check this. If the file has been modified, the backend can emit a `ReloadPrompt` request. Then, it'll be up to the client to handle this. If user says yes, we reload file contents from disk. Otherwise, we set a `reload_chk` flag to `false` (reset as `true` every time file is saved and `true` by default).

I'll try to come up with a solution and send in a PR in a couple of days.

**Comment by cmyr** [comment]
@prasoon2211 we're going to need to do fs monitoring for a bunch of other stuff (watching for settings changes, new plugins/themes etc). I'd encourage you to think about those use cases as well if you're taking a stab at this. I'd also take a look and see if there are any crates available for some of this functionality (https://github.com/passcod/notify)?

**Comment by prasoon2211** [comment]
@cmyr Alright. I'll try to think in a more generic way to implement this although I should warn you - I'm pretty new to both Rust and this project and the PR might require some help. The crate you mentioned looks good at a first glance - I'll see if it'll do for our use cases.

**Comment by cmyr** [comment]
@prasoon2211 very happy to help out however I can, fs monitoring is something that's in the back of my head as needing to get thought about soon but I haven't really gotten around to it yet. Let me know if you have any questions. @raphlinus or @trishume might also have some opinions w/r/t fuchsia. Given our pretty broad platform goals we'll probably want the ability to implement the monitoring mechanics ourselves where necessary, but it would be nice to take advantage of existing work where possible.

**Comment by prasoon2211** [comment]
I have very little knowledge about Fuchsia. The `notify` crate is cross-platform though either by using native OS support (Win/Linux/Mac) (fast) or through polling (slow).
So, I think that we should be able to use this crate. Native support for Fuchsia can probably be added sometime later.

**Comment by trishume** [comment]
@prasoon2211 yah don't worry about supporting Fuchsia. We don't even really support loading files on Fuchsia, so reloading files is kinda a long way out. When we get around to that we'll fix it so it works. As long as you don't do anything that would obviously break the build on Fuchsia, and you don't have to check that yourself, if you're worried you might break Fuchsia just ask me and I can test it.

As for other OSs, yah the `notify` crate seems like the right avenue.

I really have no idea how to do a clean architecture for this though. We don't really have a good event loop system. With the architecture we have right now you'd probably have to have a thread that waits on the `notify` stuff and holds a `BufferContainerRef<W>` that it locks when it gets an update and does a bunch of buffer-specific stuff.

Ideally there'd be some architecture where you open a file handle that both reads the initial contents of a file and starts a watch on it. Then it sends you updates when it changes until you drop the handle, which you'd do when you close the buffer for the file or unload the relevant plugin or something. Then both plugins and files could use it. However, I have no clue if this can be done with the current state of Xi.

The interesting thing that plugins will eventually want but doesn't matter for files is watching directories for new files. When you add a new plugin or a new file to a plugin file it would be nice to do what Sublime does and load it on the fly. So perhaps plugins need a different kind of architecture than files. We don't even have the infrastructure to start that yet though, just something to think about.

**Comment by troplin** [comment]
Another use case for this feature is a log viewer. Of course without user prompt in that case.

**Comment by trishume** [comment]
The typical way to implement this feature is to prompt iff the file is dirty. If there's no pending edits to the file, it should just reload automatically. This is super important when switching git branches, but could also help as a log viewer. The thing that's necessary for the log viewer case and important for other cases is preserving scroll position.

Eventually the way we want to support whole-file updates like formatting and reloading is by diffing the old and new contents and applying the changes as an edit to the `Engine` structure. This would allow preserving scroll position, as well as selection. It would also allow undo-ing past the reload, which may or may not be what we want, I'm not sure but I'm inclined to allow it.

**Comment by prasoon2211** [comment]
Guys I've been prohibitively busy the last week so wasn't able to reply. Anyway,
> If there's no pending edits to the file, it should just reload automatically.

I'm not so sure about this. Suppose I did some work in a file and saved it. Then, some other program comes in and edits and saves the file. Now, the file isn't dirty and - in git terms - the tree hasn't diverged and we can "fast-forward" the merge automatically. However, as a user, I personally wouldn't want this. I don't want unwanted changes creeping into my files without me explicitly allowing it.

I also got a chance to look at the `notify` crate. Every time a file is edited (and saved), the watcher on the file emits a `Write` event. So, we could probably add a watcher on each buffer in a separate thread but I'm not sure how feasible this will be - a user might wish to open hundreds of buffers (files)  which will mean hundreds of threads; this isn't a problem on modern systems but it might slow down older systems substantially. The other approach to watching files is to just watch the file being edited currently (though I'm not sure how we can do this). One other problem is how do we distinguish between a write by an external program and a write by our editor (since both will emit the `Write` event. This may be solvable by using the method I mentioned earlier (using a combination of last modified timestamp and md5 of file's contents) but I think that there should be a better solution to this problem.

Also, I looked at the editor code and I'm still unclear on the architecture. Let me know if I have this right. So, buffers contain data to be edited (files or otherwise, much like Emacs). Each buffer has an `Editor` associated with it that has functions for editing files and this mapping is a one-to-one mapping (the buffer-editor mapping). Each editor (and therefore each buffer) can have multiple views into contents (much like windows in Emacs) and only one view is the primary view in which the file is being edited. Is my understanding correct?

**Comment by trishume** [comment]
@prasoon2211 

I could agree with always prompting on reload being a preference like Sublime's `always_prompt_for_file_reload`. We should really get around to implementing a preference system. Certainly it being the only option would make the editor instantly unusable for me since switching git branches would require accepting between 1 and 10 annoying prompts depending on how it is implemented.

Also, my reading of the `notify` crate's API suggests you can easily have one watcher that watches all open files, sending on a single channel. This probably would end up using 2 threads, one internal to the `notify` crate and one in Xi for listening on the `mpsc`.

Your understanding of the current architecture is correct. The concept of "buffer" is slightly confusing since there are kind of two things, `Engine` is the actual contents plus history, and `Editor` is the `Engine` plus some associated state and a whole bunch of editing functions.

However, we may be reversing that soon, see #371. After that it may be that that views would share `Editor`s instead of `Editor`s owning multiple views.

**Comment by trishume** [comment]
@prasoon2211 

Some advice: If you're just looking to have fun adding a feature to Xi, I might suggest something else. We're kind of at too early a stage to have a really good architecture to add file watching on top of. I think it would be easier to implement later and less likely to require a rewrite when our architecture is more stable. I'm happy to talk about other possible interesting work with you.

However, if reload is something you specifically want, and would like to work on, then go for it! I just caution you that right now it won't be as easy as it will be later, and we may need to heavily refactor it or rewrite it depending on how much we change.

**Comment by prasoon2211** [comment]
> If you're just looking to have fun adding a feature to Xi, I might suggest something else.

Probably a good idea seeing as I don't understand the architecture well.

> I'm happy to talk about other possible interesting work with you.

Thanks for the offer. I seem to have gotten myself mired in more work at my day job again :sweat_smile: so I'm not getting much time right now.

**Comment by cmyr** [comment]
As of #427 we have some basic functionality to monitor file system events; that should probably serve as the basis for adding this feature.

**Comment by cmyr** [comment]
update to this: there's a rewrite in flight of notify-rs (https://github.com/passcod/notify/issues/117), which we're relying on to provide filesystem events; I'd like to hold off on this issue until that lands, because it will significantly change the API we're interacting with and probably require a rewrite anyway.
