### ISSUE TITLE
[Question] JNI bindings for xi-editor

### ISSUE THREAD

**Issue by ArazAbishov** [google/xi-editor#405]
Running xi-editor as a separate process makes development of frontends on mobile platforms almost impossible. For instance if I want to consume xi as a backend on android, I have to pre-package it and start as a standalone process. Unfortunately, there is no non-hacky way to spawn a process from the application on Android. 

Hence, one of the most feasible approaches would be to compile the xi-core along with the application and communicate with it through JNI (Java Native Interface). Is it possible to separate out the IPC part of xi and use direct function calls instead? Is it something what `core-lib` does?

Another question which I have is related to the fuchsia fronted for xi. In the readme of the project, there is a mention on how to build and run the app on Android. The part related to `xi` seems not very clear to me. The only action described is a command to send the binary over `adb` to device's `data/local/tmp/` directory, which seems to be a hack? Is there any other way for integration into android?

Thank you very much.

**Comment by cmyr** [comment]
@ArazAbishov You're right that there are definitely some barriers to developing mobile frontends right now; on iOS, you can't launch subprocesses at all. The way I would imagine getting around this is using `core-lib` as a static library, and running it in a pthread. Plugins would also need to support being used as libraries. This would require a bit of work, but should be generally doable.

I can't really help much on the fuchsia stuff, unfortunately. :(

**Comment by ArazAbishov** [comment]
@cmyr Thanks for the fast reply. Do you think those changes are aligned with the future of the library? I will be glad to contribute, but I don't want to maintain a fork :)

**Comment by raphlinus** [comment]
Hi @ArazAbishov!

There are a bunch of related questions here. I'll see if I can address them, but feel free to follow up.

First, the architectural choice to have the front-end and core in different processes is not rigid at all, and if you look at [xi-win](https://github.com/google/xi-win) you'll see that it's all one process, with the core running in a thread. That was one of the motivations (along with Fuchsia's needs) why `core-lib` was separated into a library rather than always running as a binary with its own "main." I'm very open to changes to better support that.

As @cmyr mentions, the question of plugins is more complicated, as architecturally I _do_ imagine these being pretty separate modules. However, for the plugins written in Rust (currently syntax highlighting) I can easily see a packaging technique that runs them in threads, perhaps even with some care taken to catch panics.

The Android port in the Fuchsia front-end does provide basic editing functionality, but at this stage it's there mostly for prototyping and development purposes. When it was written, the compile-edit-run cycle was much shorter for Flutter-on-Android than Fuchsia. The latter is improving to the point where it might make sense to only maintain the Fuchsia port. That said, it _is_ a viable path to getting a working editor on both Android and iOS in addition to Fuchsia.

Sending the binary over adb is definitely a hack, but effective for development/prototyping. It's certainly possible (but not mainstream) to package a binary that can be run in a separate process, but that would be an Android-only solution. If this were to be further developed, it would probably make more sense to have it in a library as you suggest. On Fuchsia, though, it's likely to remain a separate binary (I can go into my thinking on that, but it's probably beyond the scope of this issue).

Short answer, I'm open to collaborating with people on a mobile experience. There's a bunch of work to be done on integrating the build and getting a sane development environment set up, in addition to the front-end work itself, so happy to have people willing to work on that.

**Comment by ArazAbishov** [comment]
Hi @raphlinus, 

Thanks for the elaborate answer. I will take a look into `xi-win` for inspiration on how to consume `core-lib` APIs. I guess next challenge will be compiling and linking the xi-editor into android project and writing JNI bindings for it. 

A quick question: is the version `0.2` latest "stable" release? I have seen that a lot of changes have been merged into master since then. This is quite important since one has to decide either to build xi from sources or just by consuming a crate through cargo. In case if crate is stale, the choice is quite obvious :) This also might greatly simplify the integration into build systems like gradle.

**Comment by raphlinus** [comment]
@ArazAbishov No, 0.2 is just a snapshot, development is done from master. There's currently nothing forcing us to do releases more regularly, but it would be a good idea to release more frequently, as, among other things, it updates the docs.

Best of luck, and let me know as you have more questions. Also feel free to make use of the #xi channel on irc.mozilla.org.

**Comment by ArazAbishov** [comment]
@raphlinus Publishing the snapshot on each commit to master might be very useful, but that is probably something what goes beyond the scope of this issue. 

Thanks and talk to you later on irc!
