### ISSUE TITLE
save operation should report success/failure

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#519]
Currently the client sends the `save` blind, and has no way of knowing if the save has succeeded or not.

Core should notify the client when a save has actually completed or failed.

There's also some related thinking to do about saving: should we (optionally) autosave changes? (#495) If so, should the client be notified in this case? Should we be saving atomically? (backup current version before attempting to overwrite). How do we handle saving into different encodings?

(this is coming up because it would be part of my ideal solution to https://github.com/google/xi-mac/issues/138)

**Comment by ishanjain28** [comment]
Hi, I would like to work on this issue. 

I would also like to voice my support to add autosave feature in xi-editor's backend because everyone who is implementing xi-frontend doesn't has to implement autosave feature themselves, Adding this feature in backend means there is a little less work for them.

**Comment by cmyr** [comment]
@ishanjain28 hello! A preliminary fix for this issue was just merged (#545), so this issue should be closed. I agree with your reasoning about auto-save, it's really just a matter of priorities. :)

In any case we appreciate your interest, and I'd encourage you to look for another issue that might interest you; if you'd like a hand or have any questions please let me know.
