### ISSUE TITLE
Request: Core Text-friendly keyboard shortcuts

### ISSUE THREAD

**Issue by chriskrycho** [google/xi-editor#52]
Core Text has built-in support for the standard Emacs navigation actions and the simplest of its text manipulation actions:
- `^f`: cursor forward
- `^b`: cursor backward
- `^p`: cursor up one line
- `^n`: cursor down one line
- `^a`: cursor or to start of line
- `^e`: cursor to end of line

Text manipulation: 
- `^k`: "kill" – cut to end of line and add to OS X "kill ring" (a secondary clipboard, essentially)
- `^y`: "yank" – paste the last item in the kill ring
- `^t`: "transpose" – swap characters on either side of cursor and advance cursor by one

Support for these would immediately make the editor feel much more native on OS X to me (and presumably a lot of others).

(If I get some time I'll see what would be needed to implement, but I'm in a very busy season and we have some family health t now, so I wouldn't hold your breath for a PR for me.)

**Comment by raphlinus** [comment]
Note that `^n` and `^p` already work. The others are interpreted into actions, it's just that the actions aren't implemented.

Also note that the difference between, say, `^f` (`move_forward`) and right arrow (`move_right`) is only relevant for BiDi. The former always advances one grapheme cluster forward, so is simpler. The latter moves forward in LTR and backward in RTL. Since we don't support BiDi yet (though I'd like to at some point), it's fine to just implement both as move_forward.

Tagging this as easy in case someone would like to contribute.

**Comment by chriskrycho** [comment]
Awesome. Can you point me to the relevant implementation area? I'll at least take a look and see if it's something I *can* do.

(PS: much :heart: for the project.)

**Comment by raphlinus** [comment]
@chriskrycho Thanks! You basically want to add more cases to [do_rpc()](https://github.com/google/xi-editor/blob/master/rust/src/editor.rs#L326) in editor.rs. Don't stress if you don't get around to it, I have confidence someone will soon :)

**Comment by rtsuk** [comment]
The Cocoa bits are all done. 

When your run Xi in Xcode and hit ^f, you see in the console:

```
to core: ["move_forward",[]]
unknown cmd move_forward
```

in rust/editor.rs there is a function called do_cmd that matches agains the command string and calls an implementation function. The task for these control keys is to write the implementation function for those commands not currently implemented.

**Comment by eestrella198** [comment]
Thank you

**Comment by gsquire** [comment]
I would like to try and add the rest of the cursor functionality if nobody else has started working on it.

**Comment by raphlinus** [comment]
@gsquire Please do, and let me know if you'd like any tips.

**Comment by canaltinova** [comment]
Hi, I would like to take a stab at implementing kill ring. But I'm new to this project, can you briefly explain how to implement it please?  :)

**Comment by raphlinus** [comment]
Hi @canaltinova.

It's not exactly trivial, but I'll try to walk you through it. A significant complication is that in Cocoa apps (I'm testing TextEdit) the kill ring is shared between all the open tabs, ie you can `^k` in one tab, switch to another tab, `^y`, and the text from the first will appear.

Thus, you have to create global state for this. The easiest way is to create a `static` variable for the kill-ring state, which is either `Mutex<String>` or `Mutex<Rope>` (it's not going to matter too much which, though the latter is theoretically more efficient if the region killed is very large). Also, side note, `RefCell` is a valid alternative to `Mutex` if we know for a fact there won't be concurrent access to the kill-ring state, but I think that's a bad idea to assume (even if it happens to be true right now).

To implement `^k`, the first step is to decide what region to cut. The logic will be very similar to what was merged in #59 for `^e`. One subtlety is that if the cursor is already at the end of the line, Cocoa "kills" the newline. The way I'd implement that is to check whether the new cursor position is the same as the old one. If so, I'd call `next_grapheme_offset` to skip over the newline. You might want to factor out the code in `cursor_end` into a separate function to avoid repetition.

Once you've got the range, the code is very similar to `do_cut()` in `editor.rs`, except that instead of returning the cut string as the return value of the RPC, you'll set the kill ring to it.

Implementing `^y` should be very easy once you've got all that done - just do `self.insert()` on the kill-ring value.

Lemme know if you have any other questions.

**Comment by canaltinova** [comment]
Thanks for the explanation @raphlinus ! But statics are not allowed to have destructors in rust, and Mutex, String and Rope have destructors. Where else we can store this state?

**Comment by raphlinus** [comment]
@canaltinova Hmm, right. Maybe in the Tabs object, and pass down a `&Tabs` reference in the RPC dispatch?

Other possibilities to explore in [this SO question](http://stackoverflow.com/questions/27791532/how-do-i-create-a-global-mutable-singleton), but passing around a reference is probably cleaner.

**Comment by canaltinova** [comment]
@raphlinus ok thanks, I'll take a look at this soon.

**Comment by hjylewis** [comment]
Have any of these not yet been implemented?

**Comment by raphlinus** [comment]
@hjylewis Good question. Of the ones specifically mentioned in this issue, I think `^t` has not yet been. If you look at all the possible key-bindings (the output of `plutil -convert xml1 -o - /System/Library/Frameworks/AppKit.framework/Resources/StandardKeyBinding.dict`) there are a lot that haven't been done yet, but some of these will be pretty rare. Some of those others are tracked in other issues, like #68.

**Comment by cmyr** [comment]
The commands listed have all been implemented, further polish can be a new issue.
