### ISSUE TITLE
Clarify Delta::iter_deletions()

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#561]
I'm confused by the behaviour of this function.

From the name my expectation is that the iterator will produce, in the coordinate space of the of the base revision, a set of intervals representing all segments of the base revision that are absent in the delta revision.

That is to say, in the following example:
```
base_rev = "ABCDEFG"
delete(0, 2)
replace(3, 4, "x")
delta_rev == "CxEFG"
```

I would expect `iter_deletions` to return `(0,2)` and `(3,4)`. Currently, however, it only returns `(0,2)`.

If this is expected behaviour, I'll fix the docs, and maybe add a new helper for the behaviour I was expecting, which I'd like for keeping plugins up to date on deleted lines; if it's a bug then i'll patch.

**Comment by cmyr** [comment]
@rkusa any chance you remember anything about this?

**Comment by rkusa** [comment]
IIRC, the goal of the method (also for the `iter_inserts`),  was to get all ranges for which search results should be invalidated. I guess the `replace` will be contained by the result of `iter_inserts`? I think the workflow was as follows.

Considering the document "ABCDEFG" and searching for "BC" will lead to an occurrences list of `[(1,3)]`. Applying the delta (`delete(0, 2)` and `replace(3, 4, "x")`) to the occurrences would change it to `[(0,1)]` (not sure, but I think this was how it worked). Since this would be an incorrect occurrence (and therefore incorrect highlight in the frontend), we remove all occurrences ranges that touch a deletion. Thus we iterate through all delegations using the `iter_deletions` method. Afterwards, we apply the delta to the occurrences list (would be empty in this case). Finally, we iterate through all inserts using `iter_inserts` and remove all occurrences that touch those ranges as well.

So I guess the `replace(3, 4, "x")` will be part of `iter_inserts` and not `iter_deletions`.

TBH, I do not remember why I split this process into those three steps

1. invalidate occurrences around deletion positions
2. apply delta to occurrences
3. invalidate occurrences around insert positions

After revisiting the code, I do not see a particular reason why the distinction is necessary. 
Maybe we (I could provide a PR to align the changes with the find implementation) could merge both methods into `iter_changes` which includes both inserts, deletions and therefore also replaces?

**Comment by cmyr** [comment]
Okay, interesting, I'm impressed you recall that much a year later!

I'm interested elsewhere in having an iter that is over all regions in the base revision that are absent in the new revision, so I'm not sure about combining them. Knowing the problem you were trying to solve is very helpful though.

One thing that's curious to me is that if I comment out the entire block in `View::after_edit` where you invalidate based on `iter_deletions`, nothing happens. (this won't be helpful on master/master where we don't even currently draw highlights, but I have a test branch where we do)

**Comment by rkusa** [comment]
> I'm interested elsewhere in having an iter that is over all regions in the base revision that are absent in the new revision, so I'm not sure about combining them.

I think having the delete from the `replace` also as a result of `iter_deletions` should be fine for the search functionality.

> One thing that's curious to me is that if I comment out the entire block in View::after_edit where you invalidate based on iter_deletions, nothing happens. (this won't be helpful on master/master where we don't even currently draw highlights, but I have a test branch where we do)

I just fetched the current master/master to try it, but the find functionality does in general not work correctly. Currently, highlights of find occurrences are removed as soon as I leave the find textfield, which should be the case. It is therefore not possible to test the effect of `iter_deletions`.

I would suggest adding the delete from `replace` to be included in `iter_deletions`, if this is the behavior you need, and afterwards, I will try to fix find in master/master :-)

**Comment by cmyr** [comment]
Okay that sounds fair. I'm also happy to fix what I break, was just trying to get a better sense of what the original idea was.

If you want to play around, I just pushed a branch to my xi-mac remote called `wip/find-fixes` which is much closer to working (highlights are all drawn correctly), feel free to build that if you want to test.

**Comment by rkusa** [comment]
Cool, I'll give it a try tomorrow (European time)

**Comment by cmyr** [comment]
I didn't end up changing this function, because I found another approach to the problem I was working on. I'm going to close it  for now, might revisit in some other form at some point.
