### ISSUE TITLE
Change behaviour of get_data plugin RPC

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#562]
Working around the plugin lib right now, and have some thoughts about this API.

1. `get_data` should allow chunk position to be specified as an offset _or_ a line number; because plugin clients are generally going to be line oriented, I think this would simplify things on the client side with very little cost. Where a line number is used, it would be converted to an offset internally. We would not guarantee that whole lines are returned.

2. Augment return value with line info: `get_data` should return line information in addition to a chunk of the document. In particular, it should return the offset of the chunk, the position in the chunk of newlines (as an array of offsets) and the line number of the first newline in the chunk. It might also be useful to include the number of newlines that exist _after_ the chunk, or the total number of lines in the document, which are informationally equivalent.

Making this change would go along way to simplifying writing a plugin library.

Earlier, I had been imaging augmenting plugin _updates_ to include, with deltas, the number of newlines in any deleted regions. This is only useful when deletions occur outside of the plugin's cache, though; and it might be simpler in that case to just blow away the cache, and know that the next `get_data` request will include the correct line info? This would only be bad in some use case where a plugin was primarily working in one part of a (very) large document, and deletions were occurring frequently in another part of the document, which seems like maybe not a case we need to be too defensive about.

@raphlinus does this make sense?

**Comment by raphlinus** [comment]
First point sounds good. I am definitely swayed by the argument of having one round-trip rather than having two separate ones for resolving line number to offset and then getting the data.

Second point I'm partly convinced. Returning both line number and offset of the returned chunk sounds great, no problem (this is consistent with the way RopeInfo is implemented). Adding data for newlines _within_ the chunk does not sound great to me - it seems likely to me that the cost of serializing, sending, and deserializing this info is more than finding the newlines on the plugin side.

And, for total number of lines in the document, it feels like this should be sent in delta rather than get_data. That way, we avoid states where we have partial information about the number of lines (ie not konwing whether a reference to a particular line is valid). I'd lean toward sending absolute line count, it feels less stateful.

Absolutely agree with the goal of simplification and not trying to optimize for the validity of line number to offset correspondence in the face of large document changes. As you point out, the cache in those cases is probably lukewarm at best.

**Comment by cmyr** [comment]
Okay, good point. As long as we know what the starting line in a chunk is, finding the rest of the offsets is trivial.

Implementation plan:

- `get_data` has fields `{ offset: Option<usize>, line: Option<usize>, rev: usize, max_size: usize }`
- `get_data` returns `{chunk: String, offset: usize, first_line: usize, first_line_offset: usize }`, where `offset` is the byte offset of the chunk, `first_line` is the line number of the line containing the start of the chunk, and `first_line_offset` is the offset of the chunk from the start of `first_line`.

- `update` will now include `num_lines` in addition to `delta, buf_size, rev`.

This should give us enough to significantly simplify the implementation of a plugin lib. It also lets us remove the `get_num_lines` plugin -> core RPC request.

**Comment by raphlinus** [comment]
Sounds good. I think the double-Option pattern is ok, but it would be nicer to express a true sum type. To spitball an alternative, how about `start: usize` and `units: Enum(utf8, line)`? Part of that thinking is that other units, such as utf16 or codepoint, would become possible.

**Comment by cmyr** [comment]
I like that, will update my earlier comment.

**Comment by vlovich** [comment]
For what it’s worth this is where CapNproto is supposed to shine.  The perf
optimization of rolling everything into 1 RPC to reduce round trips is
orthogonal to composable fundamental APIs that require multiple RPCs:
capnproto transforms this so you can reference prior results without
waiting for the result.  Not 100% as efficient as rolling into 1 API but
still roughly 1 round trip latency even though you may have made multiple
RPC calls.  So for now I agree this is the right move but at some point we
should put some thought into going back to composable RPC calls if we
switch to capnproto or just adopt the time travel mechanism to JSON.

**Comment by raphlinus** [comment]
@vlovich Interesting - I had looked at Cap'n Proto and would still consider it.

Here I think there are two overlapping concerns. One is efficiency, primarily measured as reducing the number of roundtrips to service a request from the plug-in. The other is trying to define access to the document state in the simplest possible way. If you weren't at all concerned about RPC efficiency, it would make sense to break that down into orthogonal primitives - some calls to translate between line and byte offset, other calls (denumerated in bytes) to get access to the data. But I think @cmyr's proposal is a good compromise - given that the one of the primary plugin-side tasks is "get data for line", being able to ask that directly compares favorably to having two separate calls, and the proposal also avoids the need for fiddly tracking of line number info across deltas.

**Comment by vlovich** [comment]
Yup.  I’m 100% agreeing that this is currently the most reasonable
solution.  CapNproto doesn’t yet have swift bindings and it’s unclear when
it will get it so I wouldn’t press for it unless we don’t need it in swift
(maybe we can hide it in xilib?)

I might dig into the how of the time travel works (I’m mainly unclear how
the server knows when to discard the result it computed - I’m hoping Kenton
had some interesting insights here ).

Maybe it’s possible to adapt to jsonrpc in some way to add promise
pipelining. It won’t be as good as capnproto though because it’s free to
deserialize whereas there’s a large non0 cost to deserialize Json which we
won’t be able to completely recover if we have a lot of primitives; so the
question will be having to measure if the cost is negligible enough .
Using grpc + FlatBuffer + adding promise pipelining to grpc might be
another option.  I’ve heard mixed online stuff about grpc performance but
it’s unclear to me if that’s a consequence of protobuf being the
serialization layer or if there’s additional overhead within grpc itself.

**Comment by cmyr** [comment]
I'm also curious about the time travel stuff, but it seems like implementation would be tricky. I can see how that would be a clear win when there's a network involved, but given that we're dealing with much smaller latencies and also that we have the flexibility to evolve our protocol to suit our needs, I'm not sure it would be solving a problem we have, right now? Open to having my mind changed, though.

I'm trying to think of other places where we regularly perform some RPC and then immediately perform another with the result, and I can't really think of any (although I can think of some that could exist around vim-mode).
