### ISSUE TITLE
Polish and cleanup in xi-trace

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#581]
I know that @vlovich was already considering/planning some of these changes, but after actually using the tracing tools I wanted to note down some of my observations:

~- [ ] _Add macros to wrap various tracing functions?_ currently even if tracing is disabled, the trace function is processed, which could include the allocation of a payload. This could be replaced with a macro that checks if tracing is enabled and noops if not. It's possible we would only want to do this for the `_payload` variants of the trace functions, since allocating payloads is the thing that could be potentially expensive in some cases.~

- [ ]  _Add ability to specify process/thread names_ The chrome tracing format allows you to add certain special [metadata traces](https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#bookmark=id.iycbnb4z7i9g), which can be used to associate a name with a process or thread. Adding support for this would make interpreting traces easier.

- [ ] _Settle on a payload type_ we'd talked about this at some point; the various payload types and related features is confusing to library consumers. My preference is once more for a `serde_json::Value`, since that's what chrome_trace will want, but a `CowStr` works too.

**Comment by vlovich** [comment]
I have been in the process of cleaning it up a lot, just other things get
in the way.  Here are my thoughts on the points raised:

Adding macros: I’m not sure I understand this point.  While the function
jump happens, the first thing is the infrastructure checks an atomic
Boolean.  The overhead of this should be in the noise unless it somehow
ends up in a hot path loop, in which case your trace is probably in the
wrong spot anyway; the caveat is I could see this happening if you use the
infrastructure as a form of debugging/logging too.  For what it’s worth
memory isn’t allocated until tracing is enable (in Xi-core - I can’t recall
if I changed xi-mac to use that optimization).

Process/thread name.  Already working on it but it’s going to be
transparent to the API.  I’m hesistant to expose to much of the chrome
tracing API cause then it’s complex to use (too many options for the same
thing) but I am working on aligning the internal representation so it’s
possible to take advantage of things more easily that make sense.  I
wouldn’t be surprised if the spec has grown organically to encompass a wide
variety of uses specific to the needs of the many sub teams of chrome
rather than having any kind of opinionated overarching philosophy.

Payload type: I think here I would say we should pick what makes sense for
the developer using the API, not what the format wants because this is all
unstructured data that Chrome ignores.  It’s there for you only to dig in
extra to diagnose issues.  Also happy to remove it if there’s no use for it
since it borders on “this is a logging facility too” .
