### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by stapelberg** [google/xi-editor#7]
I’d prefer to just try a ready-made binary release instead of pulling the source and a development environment on my computer. Is there any chance you can add binary releases? Thanks!

**Comment by Fequois** [comment]
I bet it's coming as the code matures. At least I'd like to think so. 😄

**Comment by sergiocampama** [comment]
+1

**Comment by Blackskyliner** [comment]
@sergiocampama since there are reactions for issue postings the +1 postings are nowadays highly discouraged by the GitHub Community. You should change your behavior in showing your support/need for issues. Just for the possibility that you didn't knew.

But to add to this issue: I think/hope the moment they do automated testings there could be a high chance that binary builds could be made available. At the very least when they get something version tagged there should be GutHub releases as binary distribution. At least that's what I would recommend, as most projects I know/use do it this way.

**Comment by leavengood** [comment]
This project is in the really, really early stages. I know a lot of people are showing interest and are excited (the increase in watches, stars, and forks since this was on Hacker News are amazing), but right now this is probably only interesting to people who want to help Raph develop it.

So I think expecting binaries may be a bit early. But I guess at the end of the day it is up to Raph.

**Comment by raphlinus** [comment]
What @leavengood said. It's not usable enough yet for it to be of much interest to people not inclined to build it from source. I'm hoping it reaches that point before long, at which point binary releases will make sense. Leaving the issue open until then.

**Comment by jansol** [comment]
Closing this as binary releases of xi-core are not particularly useful (as stated elsewhere already).
