### ISSUE TITLE
Please consider creating a Flatpak package for Xi Editor

### ISSUE THREAD

**Issue by lukehutch** [google/xi-editor#700]
To enable users to easily test out and use Xi Editor on any Linux distribution, it would be great if a Flatpak package could be provided for download.

https://flatpak.org/

Flatpak is supported out of the box on all the major Linux distributions today, making it very simple for the Xi editor team to support multiple distributions (no need to create a separate rpm, dpkg, etc.).

**Comment by mqzry** [comment]
The project is not stable enough to release binaries according to the owners/maintainers. See https://github.com/google/xi-editor/issues/7.

Since it has been 2 years since @raphlinus commented about it: is this still the case Raph?

Btw, releasing this project as a binary will not help you much to use it as an editor. This project only contains the 'core' that can only be communicated with through JSON RPC. If you want to have frontend, ask some of those projects to package it for you. See https://github.com/google/xi-editor/issues/142 for a list of linux frontends.

**Comment by lukehutch** [comment]
Fair enough, I will close this. I hope the project keeps progressing. Thanks!

**Comment by eyelash** [comment]
There's a [flatpak manifest](https://github.com/eyelash/xi-gtk/blob/flatpak/com.github.eyelash.xi-gtk.json) for xi-gtk. It might need some updates for recent changes, though.
