### ISSUE TITLE
Theme no longer sent with config_changed notification

### ISSUE THREAD

**Issue by euclio** [google/xi-editor#722]
- macOS 10.13.5
- rustc 1.27.0 (3eda71b00 2018-06-19)
- Installed via rustup
- No frontend
- commit a66bbd6

This worked in a previous version of the editor, but after updating to master today I don't see the notification.

Steps to reproduce:

1. Add the following to `preferences.xiconfig` in your config dir.
   ```
   theme = "Solarized (dark)"
   tab_size = 2
   ```
1. `test.rpc`:

   ```
   { "method": "client_started", "params": { "config_dir": "<path to config dir>" } }
   { "id": 0, "method": "new_view", "params": {} }
   ```

`$ cargo run --release < test.rpc`

Notice that there is no entry in the `config_changed` notification for `theme`, but `tab_size` is present:

```
{"method":"available_themes","params":{"themes":["InspiredGitHub","Solarized (dark)","Solarized (light)","base16-eighties.dark","base16-mocha.dark","base16-ocean.dark","base16-ocean.light"]}}
{"id":0,"result":"view-id-1"}
{"method":"available_plugins","params":{"plugins":[],"view_id":"view-id-1"}}
{"method":"config_changed","params":{"changes":{"auto_indent":false,"font_face":"InconsolataGo","font_size":14.0,"line_ending":"\n","scroll_past_end":false,"tab_size":2,"translate_tabs_to_spaces":true,"use_tab_stops":true,"word_wrap":false,"wrap_width":0},"view_id":"view-id-1"}}
{"method":"update","params":{"update":{"ops":[{"lines":[{"cursor":[0],"styles":[],"text":""}],"n":1,"op":"ins"}],"pristine":true},"view_id":"view-id-1"}}
{"method":"scroll_to","params":{"col":0,"line":0,"view_id":"view-id-1"}}
```

**Comment by euclio** [comment]
I just did a `git bisect` and it seems that this behavior was broken in e3c824c1a0e6a1773e8f752a2600c5feb906b22d. I'm confused, did it work unintentionally before?

If you checkout 213638a87a260f3f041e2f0507e77b47e5c3ae0b and do my reproduction steps, you can see the desired behavior.

**Comment by cmyr** [comment]
Ah, I think I understand.

This is actually a slightly funny situation: the original behaviour _was_ unintentional (it was not intended that additional key/value pairs in the config file that weren't known to core would still be forwarded to the client) but then we also added a feature in xi-mac (`unified_titlebar`) that took advantage of this.

We would like for clients to be able to use custom config keys, and until we add something like namespacing the current solution seems reasonable.

The bug here is that when a view is first created, we don't send the whole config table; we just send the config items that are defined in core. Other items will be sent when they change, but not when a view is newly created.

Will have to think of a non-hacky way of doing this.

In either case, setting `theme` in core will not currently do anything, even if it does report the config setting back to the client.

**Comment by cmyr** [comment]
Okay, there was actually a pretty quick fix for this; try out #726 and let me know if that works?

**Comment by euclio** [comment]
Nice, that works.

Yeah, my frontend that relied on the old behavior just called `set_theme` when receiving a `config_changed` the `theme` key.

**Comment by cmyr** [comment]
heh okay, fair enough. That's definitely going to break at some point, but it isn't a priority right this second. 😄
