### ISSUE TITLE
warning: profiles for the non root package will be ignored, specify profiles at the workspace root

### ISSUE THREAD

**Issue by cmyr** [google/xi-editor#733]
Another little complication from #730; this warning now shows up when building the main project.

Moving this profile to the top level manifest should be fine, but maybe @vlovich can clarify why we were turning on lto for benchmarking?

**Comment by vlovich** [comment]
I think I put it in cause, especially for micro-benchmarks like this, you want to test the most optimized code & not to waste time tweaking things from readable to less readable because you're optimization level wasn't high enough.  YMMV though - feel free to take it out if it doesn't make sense anymore.
