### ISSUE TITLE
consider libui for ui

### ISSUE THREAD

**Issue by ordian** [google/xi-editor#84]
One of design decisions for xi-editor is:

> Native UI. Cross-platform UI toolkits never look and feel quite right. The best technology for building a UI is the native framework of the platform. On Mac, that’s Cocoa.

According to [libui](https://github.com/andlabs/libui) description, it is:

> Simple and portable (but not inflexible) GUI library in C that uses the native GUI technologies of each platform it supports.

It also has rust [bindings](https://github.com/pcwalton/libui-rs), so why not using libui?

**Comment by JesseFarebro** [comment]
I feel as though a native cross platform UI will be very challenging with respect to plugins. If a plugin developer wants to target any part of the UI the consistency across platforms will be hard to achieve. I haven't seen any talks of plugins which alter the UI outside of the core editing behavior but one has to assume it will be an eventual goal to be competitive with the other big editors. 

I've never heard of libui but it may be a step in the right direction.

**Comment by raphlinus** [comment]
I've looked at libui, but am skeptical that it can provide the highest performance and level of polish. There's a strong tendency of cross-platform UI's to provide a lowest common denominator, often because it uses older versions of platform libraries. For example, on Windows is the text drawing based on GDI or DirectWrite? On Mac, does it provide access to Automatic Termination?

I think the way to pursue this is to try a libui front-end as a prototype, and compare it to the Cocoa one for quality and performance (I am considering the latter to be the standard). If it really holds its own, we could consider using it for the other platforms.

But my strong gut feeling is that fully native UIs will be considerably better.

**Comment by ordian** [comment]
> For example, on Windows is the text drawing based on GDI or DirectWrite? On Mac, does it provide access to Automatic Termination?

[DirectWrite](https://github.com/andlabs/libui/blob/e114502605f90b728a52e4788ea9f9cc06b4e2b1/windows/winapi.hpp#L36), I guess Automatic Termination is not supported (there is shouldQuit API function), even though libui requires Mac OS X 10.8+, but I don't think it is a performance issue.

**Comment by thomas-profitt** [comment]
I don't think there's anything wrong with a libui front-end at all, even as a reference front-end, but I strongly disagree that we should have one single, central front-end at all. The architecture we have, with explicit and clean separation between the core and front-end implementations, is very important to facilitate the amount of flexibility and diversity of implementations a developer's editor should have.

An ecosystem of different front-ends and IDEs implementing xi and their own front-end as their built-in editor is very easy to imagine if we stick to the current architecture.
