### ISSUE TITLE
selections and color schemes

### ISSUE THREAD

**Issue by eyelash** [google/xi-editor#96]
For the GTK+ front-end I'm developing I would like to invert the text color for the selection to achieve some more contrast but I noticed this would interfere with the "fg" line attribute.
So I propose the following incremental changes:
1. The core assumes text is rendered black on white and sends both a "sel" and a bright "fg" attribute for selections.
2. The "sel" attribute is replaced with a "bg" attribute that also contains a color.
3. The core somehow informs the front-end about a default background and foreground text color (and possibly a cursor color)

After these changes the core would have complete control over the colors and color schemes could be implemented and shared across all front-ends.

**Comment by raphlinus** [comment]
I'm thinking about this, still haven't come a conclusion. There are some problems with background color spans in the Cocoa front-end, which is one reason I haven't done that yet. See [this thread](https://github.com/google/xi-editor/commit/a9dcdbd1846b15efd7355ed707301b064ae81c3b#commitcomment-18367250) for more discussion.

More deeply, who should be the final source of truth for the theme? It's easiest to let the plugin do it (this would be implemented by your (3) above, a command to the front-end to set the theme). But this could lead to flashing if the plugin takes more than a frame to load.

There's also more to the selection appearance than just the background color. If you look at Sublime, the selection has rounded corners, while background colors set by the theme are rectangular. Also, within a selection, spaces are rendered with a tiny dot, and tabs by a horizontal line.

In any case, I'll take PR's that evolve in the right direction. What you propose would be a good start.

**Comment by sp3d** [comment]
I'd like to give my perspective on this, as someone who primarily uses GTK+-based GUI programs and wants to see Xi be usable as a powerful backend for text-editing widgets.

Editors for code obviously have more specialized needs than most of the built into toolkits, but the GtkSourceView library has done a really good job of handling both code-specific needs like paren matching, search result highlighting, code folding, and syntax highlighting while still fitting into the user's system theme, and I think we should take some hints from what it does.

GtkSourceView has its own style scheme and syntax highlighting system (and Xi will presumably have its own), but styles mutate colors and font attributes starting from the initial state established by the GTK+ theme's palette and settings.

@raphlinus, I'm not 100% sure what you mean by "final source of truth for the theme", but in order to follow GTK+ theming effectively, the GTK frontend needs to be able to present a base set of colors which are merged with recommendations from syntax highlighting, paren matching, etc.

GTK+ applications implement more nuanced logic for selections in particular than it sounds like Xi does at the moment. In particular, GNOME applications use a different color to highlight selected text in focused vs. unfocused windows, and this is one of the primary visual indicators of window focus. In GTK2 theming this was base[SELECTED]+text[SELECTED] vs base[ACTIVE]+text[ACTIVE]; in GTK3 these correspond to the "selection" pseudoelement and the ":focus selection" selector.

GTK+ themes can also be dynamically switched/modified, and applications are supposed to listen for the corresponding signals and update their custom drawing accordingly.

Personally, if possible, I'd think it may be simplest for the core to annotate "high-level" aspects of display (selected/not, grammatical category for syntax highlighting, "this is a matched brace", etc.), and leave the management of actual colors (since different TUI/GUI/etc. systems have different notions of color and colorspaces) to frontends.

**Comment by eyelash** [comment]
I'm closing this now as the original issue has been resolved with #345.
